<style type="text/css">
    button {
        border: 1px solid #1dcaca;
        background: #1dde9c;
        color: #fff;
        cursor: pointer;
        margin: 0 0 5px 0;
    }
	button.btn.btn-success {
		padding: 1px 1px;
	}
	.description
	{
		width: 100%;
	}
</style>
<?
	function fill_field($name, $default_values)
	{
		$default_values = (array)($default_values);
		
		if(isset($_POST[$name]))
			return htmlspecialchars($_POST[$name]);
		else if(isset($default_values[$name]))
			return htmlspecialchars($default_values[$name]);
		
		return '';
	}
	
	$PAW_PRICE_USD = \Paw\Price::getPriceUSD($this->getDb());
?>
<div class="main_box">
	<div class="inner_main_box">
		<h2>Edit listing</h2><br />
		<form enctype="multipart/form-data" action="/edit_listing_submit?id=<?= $LISTING->id ?>" method="POST">
			<div class="form-group">
				<? if($LISTING->image_path) { ?>
					<div style="border-bottom: 1px solid #333; padding-bottom: 15px; margin-bottom: 15px;"><img src="uploads/<?= $LISTING->image_path ?>" height="100px"></img> <a href="/edit_listing?id=<?= $LISTING->id ?>&remove_image" class="btn btn-warning">Remove image</a></div>
				<? } ?>
				<label for="image">Choose a new image for your listing:</label><br />
				<input name="uploaded" type="file" >
			</div>
			<div class="form-group">
				<label for="type">Type</label><br />
				<select name="type">
					<option value="0" <?= $LISTING->type == '0' ? ' selected="selected"' : ''; ?>>Selling</option>
					<option value="1" <?= $LISTING->type == '1' ? ' selected="selected"' : ''; ?>>Buying</option>
				</select>
			</div>
			<div class="form-group">
				<label for="price_usd">Price in USD</label><br />
				<input id="price_usd" name="price_usd" placeholder="5.00" type="text" value="<?= fill_field('price_usd', $LISTING) ?>" /> <span id="price_usd_paw"></span>
			</div>
			<div class="form-group">
				<label for="price_paw">Price in PAW</label><br />
				<input id="price_paw" name="price_paw" placeholder="10,000,000" type="text" value="<?= fill_field('price_paw', $LISTING) ?>" />
			</div>
			<div class="form-group">
				<label for="title">Title</label><br />
				<input name="title" placeholder="Item I'm selling or like to buy" type="text" value="<?= fill_field('title', $LISTING) ?>" />
			</div>
			<div class="form-group">
				<label for="body">Description</label><br />
				<textarea name="body" class="description"><?= fill_field('body', $LISTING) ?></textarea>
			</div>
			<input type="hidden" name="_token"  value="<?php echo $_SESSION['_token']; ?>" />
			<br /><br /><button type="submit" class="btn btn-main">Edit listing</button>
		</form>
		<script type="text/javascript">
			var paw_price_usd = <?= $PAW_PRICE_USD ?>;
			var load_after = function(){
				$('#price_usd').change(function(){
					var price = $('#price_usd').val();
					$('#price_paw').val(Math.floor(price/paw_price_usd));
				});
				$('#price_paw').change(function(){
					var price = $('#price_paw').val().replace(/,/g, '');
					$('#price_usd').val(Math.floor(price*paw_price_usd*100)/100);
				});
			}
		</script>
		
		<div style="color: #19adb3; font-weight: bold;" id="error_message"><?php echo $err ? '<span>'.$err.'</span>' : ''; ?></div>
	</div>
</div>