		<div id="disclaimer">Use caution! This is an open listing platform and scammers can create listings or contact you.</div>
	</main>


	<a href="#" class="back-to-top"><i class="fas fa-chevron-up"></i></a>

	<!-- JavaScript Libraries -->
	<script src="/lib/jquery/jquery.min.js"></script>
	<script src="/lib/jquery/jquery-migrate.min.js"></script>
	<script src="/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
	<script src="/lib/superfish/hoverIntent.js"></script>
	<script src="/lib/superfish/superfish.min.js"></script>

	<!-- Template Main Javascript File -->
	<script src="/js/main.js?1.78"></script>

</body>
</html>