<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>PAW Market Place</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
	<meta content="" name="keywords">
	<meta content="" name="description">

	<!-- Favicons -->
	<link rel="apple-touch-icon" sizes="180x180" href="/img/favicons/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/img/favicons/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/img/favicons/favicon-16x16.png">
	<link rel="manifest" href="/img/favicons/site.webmanifest">
	<link rel="mask-icon" href="/img/favicons/safari-pinned-tab.svg" color="#5bbad5">
	<link rel="shortcut icon" href="/img/favicons/favicon.ico">
	<meta name="msapplication-TileColor" content="#da532c">
	<meta name="msapplication-config" content="/img/favicons/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">

	<!-- Bootstrap CSS File -->
	<link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	
  <!-- Libraries CSS Files -->
	<link href="/lib/font-awesome/css/fontawesome.min.css" rel="stylesheet">
	<link href="/lib/font-awesome/css/brands.min.css" rel="stylesheet">
	<link href="/lib/font-awesome/css/solid.min.css" rel="stylesheet">
	<link href="/lib/ionicons/css/ionicons.min.css" rel="stylesheet">
  
	<!-- Main Stylesheet File -->
	<link href="/css/style.css?v1" rel="stylesheet">
	<script src="/js/qrcode.min.js"></script>
</head>

<body>
	<header id="header">
		<div class="container">
			<div id="logo" class="pull-left">
				<h1><a href="/" class="scrollto">PAW Market</a></h1>
			</div>

			<nav id="nav-menu-container">
				<ul class="nav-menu">
					<li class="menu-active"><a href="/">Home</a></li>
					<? if($this->user): ?>
						<li><a href="/logout">Logout</a></li>
						<li><a href="/profile?id=<?= $this->user->id ?>">| <?= substr($this->user->paw_address, 0, 12); ?>...</a></li>
					<? else: ?>
						<li><a href="/login">Login</a></li>
					<? endif; ?>
				</ul>
			</nav>
		</div>
	</header>
	
	<main id="main">